// ============================================
// 01-CONFIG.JS — Константы и конфигурация
// ============================================
// За что отвечает:
// - SHARE_LINK, botUrl, ASSETS
// - SKIN_DATA, TRANSLATIONS (ru/en)
// - gameConfig для Phaser.Game
// ============================================

const SHARE_LINK = "https://t.me/GlitchedArenaBot";
const RENDER_URL = 'https://glitched-arena.onrender.com';
const getBotUrl = () => {
    const hostname = window.location.hostname;
    if (hostname === 'localhost' || hostname === '127.0.0.1') {
        return 'http://localhost:8000';
    }
    return RENDER_URL;
};
const botUrl = getBotUrl();

const ASSETS = {
    BGM: 'assets/Cyberpunk 2.mp3',
    SFX_ULTRA: 'assets/futuristic-cyberpunk-digi-ivvyqv4k.wav',
    SFX_COMBO: 'assets/Cyberpunk_Alert.mp3',
    SFX_NUKE: 'assets/Star_Wars-Siren.mp3'
};

const rainbowColors = [0xff0000, 0xff7700, 0xffff00, 0x00ff00, 0x00ffff, 0x0077ff, 0xff00ff];

const SKIN_DATA = {
    classic: { body: 0x00ffff, eyes: 0xffffff, trail: 0x00ffff, bullet: 0x00ffff, alpha: 1 },
    phantom: { body: 0x9900ff, eyes: 0x00ffff, trail: 0x9900ff, bullet: 0x9900ff, alpha: 1 },
    gold:    { body: 0xffff00, eyes: 0x000000, trail: 0xffaa00, bullet: 0xffff00, alpha: 1 },
    neon:    { body: 0xff0055, eyes: 0xffffff, trail: 0xff0055, bullet: 0xff0055, alpha: 1 },
    ghost:   { body: 0x00ffff, eyes: 0xff00ff, trail: 0xffffff, bullet: 0xffffff, alpha: 0.5 },
    crimson: { body: 0xff2222, eyes: 0xff0000, trail: 0xff0000, bullet: 0xff4444, alpha: 1, passive: 'critBossDmg' },
    void_skin: { body: 0x4400aa, eyes: 0xaa00ff, trail: 0x8800ff, bullet: 0x6600cc, alpha: 0.9, passive: 'dodgeBoss' },
    plasma:  { body: 0x00ccff, eyes: 0xff00ff, trail: 0x00ffff, bullet: 0x00ffff, alpha: 1, passive: 'ultraCharge' },
    solar:   { body: 0xffaa00, eyes: 0xffff00, trail: 0xff8800, bullet: 0xffaa00, alpha: 1, passive: 'minionCoins' },
    frost:   { body: 0x88ddff, eyes: 0xffffff, trail: 0xaaddff, bullet: 0x88ccff, alpha: 1, passive: 'slowmoDuration' },
    rainbow:  { body: 0xff0000, eyes: 0xffffff, trail: 0xff0000, bullet: 0xff0000, alpha: 1, rainbow: true },
    void_premium: { body: 0x220044, eyes: 0xff00ff, trail: 0x4400ff, bullet: 0x8800ff, alpha: 0.85, passive: 'voidShield' },
    crystal:  { body: 0x00ffaa, eyes: 0xffffff, trail: 0x88ffff, bullet: 0x00ffaa, alpha: 1, passive: 'crystalReflect' }
};

const SKINDATA = SKIN_DATA;

const TRANSLATIONS = {
    en: {
        menu_title: "GLITCHED\nARENA", start: ">> START SYSTEM", shop: ">> DATA SHOP",
        hangar: ">> SHIP HANGAR", settings: ">> PILOT SETTINGS", rules: ">> SYSTEM MANUAL",
        top: ">> GLOBAL RANKINGS", audio: "AUDIO", back: "<< BACK TO MENU",
        offset_label: "OFFSET", higher: "HIGHER", lower: "LOWER", apply: "<< APPLY & EXIT",
        share_duel: "⚔️ CHALLENGE FRIEND", profile: "[ PROFILE ]",
        credits: "CREDITS", sector: "SEC", best: "BEST", max_dist: "MAX DIST",
        hp_label: "HP", core_label: "CORE", tap_ultra: "!! TAP TO BLAST !!",
        combo_text: "COMBO", hyper_glitch: "!!! HYPER_GLITCH: 3x GOLD !!!",
        pause_text: "PAUSE", v_on: "ON", v_off: "OFF",
        p1: ["SCANNING...", "TARGET_LOCKED", "DATA_TRESPASSER"],
        p2: ["SYSTEM_OVERLOAD", "CRITICAL_RAGE", "DELETING_YOU"],
        wall_p1: ["ZONE_SHIFT", "CHOOSE_WISELY", "THE_WALL_AWAITS"],
        wall_p2: ["NO_ESCAPE", "OBLITERATION", "WALL_CRUSH"],
        dual_p1: ["TWIN_POWER", "CORE_SYNC", "DUAL_DETECTED"],
        dual_p2: ["OVERLOAD", "CORE_BREACH", "SYSTEMS_FAIL"],
        storm_p1: ["STORM_INCOMING", "ZONES_ROTATE", "CHAOS_APPROACHES"],
        storm_p2: ["TORNADO_MODE", "STORM_BREAKS", "DESTRUCTION_SPINS"],
        void_p1: ["VOID_OPENS", "ABSORB_POWER", "DARKNESS_FEEDS"],
        void_p2: ["VOID_UNLEASHED", "DARK_MATTER", "CONSUMED_BY_NOTHING"],
        core_destroyed: "CORE DESTROYED!", boss_detected: "MEGA_BOSS_DETECTED",
        defense_engaged: "ELITE_DEFENSE_ENGAGED", critical_race: "CRITICAL_RAGE",
        system_halt: "!! SYSTEM_HALT: CORE_OVERLOAD !!", warning_boss: "!! WARNING !!\nBOSS APPROACHING",
        quantum_alert: "QUANTUM_PHANTOM_DETECTED", integrity_restored: "INTEGRITY RESTORED",
        wall_zone: "DANGER ZONE!", wall_safe: "SAFE ZONE!",
        audio_glitch: "SYSTEM_AUDIO_FAILURE", sys_failure: "!! SYSTEM_FAILURE !!",
        heroic_survival: "HEROIC_SURVIVAL", lost: "CONNECTION_LOST",
        revive_label: "REVIVE", watch_ad_label: "WATCH AD (FREE REBOOT)",
        hard_reboot_label: "HARD REBOOT (SEC 1)",
        share_invite: "I'm on Sector %lvl%! Beat my record of %dist%m in Glitched Arena!",
        share_win_text: "I cleared Sector %lvl% in Glitched Arena! Can you beat it?",
        share_loss_text: "System failure in Sector %lvl%... Can you survive longer?",
        db_connecting: "CONNECTING_TO_DATABASE...", db_empty: "NO RECORDS YET", db_error: "CONNECTION_ERROR: OFFLINE",
        shop_title: "DATA SHOP", maxed: "MAXED", deploy_btn: ">> DEPLOY SECTOR",
        hangar_title: "SHIP HANGAR", hull_type: "--- HULL_TYPE ---", visual_skin: "--- VISUAL_SKIN ---",
        target: "TARGET", suggest: "SUGGEST", classic_box: "CLASSIC BOX", cyan_neon: "CYAN NEON",
        boss_scanning: "SCANNING_SECTOR_", rules_header: "SYSTEM_MANUAL v1.2",
        callsign_label: "--- CALLSIGN ---", tap_edit: "[ TAP TO EDIT ]",
        to_mega_boss: "TO MEGA_BOSS", elite_phase: "ELITE PHASE", distance_to: "DISTANCE TO BOSS",
        purified: "SYSTEM_PURIFIED", magnet_on: "MAGNET_LINK_ACTIVE", time_warp: "TIME_WARP_ACTIVE",
        underst: "[ I UNDERSTAND ]",
        gary_intro: "Look what we have here... a new 'pilot'. Try not to break my system, okay? Use the Credits to upgrade, or you won't last a second. Good luck, meatbag.",
        gary_intro_ship: "Oh, so you named this junk heap «%ship%»? Cute. I hope it burns as beautifully as it's named. Listen up...",
        up_antenna: "ULTRA ANTENNA", desc_antenna: "Ult charges 75% faster",
        up_cannons: "DUAL CANNONS", desc_cannons: "Extreme 3-way firepower",
        up_speed: "SPEED BOOST", desc_speed: "+10% running speed",
        up_hull: "REINFORCED HULL", desc_hull: "+25 Max HP & Full Heal",
        up_shield: "EMERGENCY SHIELD", desc_shield: "Protects from one hit",
        skin_striker: "VOID STRIKER", desc_striker: "Dangerous Triangle (+20% ATK)",
        skin_gold: "GOLD SKIN", desc_gold: "Pure gold style (+10% ATK)",
        skin_ghost: "NEON GHOST", desc_ghost: "Cyberpunk ghost (+15% SPD)",
        skin_crimson: "CRIMSON", desc_crimson: "Bloody +5% crit damage to boss",
        skin_void: "VOID", desc_void: "Dark +3% dodge boss bullets",
        skin_plasma: "PLASMA", desc_plasma: "Neon +5% ultra charge speed",
        skin_solar: "SOLAR", desc_solar: "Golden +10% coins from minions",
        skin_frost: "FROST", desc_frost: "Icy +1s slowmo duration",
        skin_rainbow: "RAINBOW", desc_rainbow: "Rainbow trail +3x combo bonus",
        void_premium: "VOID LORD", desc_void_premium: "Dark shield blocks 1 hit",
        crystal: "CRYSTAL", desc_crystal: "Reflect bullets +1s slowmo",
        up_omega: "OMEGA CORE", desc_omega: "Requires Level 40. Ultra recharges on every minion kill!",
        ship_tank: "IRONCLAD HULL", desc_tank: "+35 HP, -8% Speed",
        ship_dart: "SWIFT HULL", desc_dart: "+20% Speed, -10% Attack",
        ship_viper: "SIDESTRIKE HULL", desc_viper: "Side mini-shots every 5 shots",
        ship_phase: "PHASE HULL", desc_phase: "10% dodge obstacle damage",
        up_coins: "DATA PACK", desc_coins: "+1000 Credits instantly",
        fx_blue_exp: "CYAN EXPLOSION", desc_blue_exp: "Your ship explodes with neon cyan",
        fx_pink_exp: "PINK EXPLOSION", desc_pink_exp: "Your ship explodes with glitch pink",
        fx_rainbow_exp: "RAINBOW EXPLOSION", desc_rainbow_exp: "Colorful rainbow explosion",
        fx_gold_exp: "GOLD EXPLOSION", desc_gold_exp: "Golden spark explosion",
        fx_green_exp: "NEON GREEN EXPLOSION", desc_green_exp: "Toxic green explosion",
        fx_red_exp: "RED ALERT EXPLOSION", desc_red_exp: "Dangerous red explosion",
        bundle_starter: "STARTER PACK", bundle_starter_desc: "Gold Skin + Antenna + Speed Boost",
        bundle_warrior: "WARRIOR PACK", bundle_warrior_desc: "Crimson Skin + Double Cannons + Hull Upgrade",
        bundle_legend: "LEGEND PACK", bundle_legend_desc: "Rainbow + Void Lord + Omega Core",
        helper_drone: "COMBAT DRONE", desc_helper_drone: "Auto-fires 2 bullets every 0.8s",
        helper_autoshield: "AUTO-SHIELD", desc_helper_autoshield: "Blocks 1 hit per sector",
        helper_autobomb: "POST-DEATH BOMB", desc_helper_autobomb: "Clears bullets, deals 80% boss DMG",
        helper_autoheal: "AUTO-REPAIR", desc_helper_autoheal: "Heals 10 HP every 2.5s",
        up_extralife: "EXTRA LIFE", desc_up_extralife: "+1 revive per sector (max 5)",
        up_doubleDMG: "OVERDRIVE", desc_up_doubleDMG: "2x damage for 30s after death",
        up_enhanced: "TITAN UPGRADE", desc_up_enhanced: "2x upgrade effects, sec 50+",
        rule_wall: "RED_WALL: Lethal. Avoid it!", rule_coin: "CREDITS: For upgrades.",
        rule_heart: "HEART: +25% Hull Integrity.", rule_nuke: "SYSTEM_NUKE: Purge all threats.",
        rule_magnet: "MAGNET: Pull credits.", rule_slowmo: "SLOW_MO: Stabilize time.",
        combo_tip: "COMBO: Dodge obstacles to build, resets on hit!",
        rules_alerts: "--- SECTOR_ALERTS ---", slide: "SLIDE TO MOVE",
        rules_sec_15: "SEC 15: MEGA_BOSS (Side Turrets)", rules_sec_20: "SEC 20: ELITE_SHIELDS (Orbital Defense)",
        rules_sec_30: "SEC 30: CORE_OVERLOAD (Bullet Hell)", rules_sec_35: "SEC 35: QUANTUM PHANTOM (Teleport)",
        rules_sec_40: "SEC 40: THE WALL (Zone Dodge)",
        rules_sec_50: "SEC 50: DUAL CORE (Twin Cores)",
        rules_sec_60: "SEC 60: THE STORM (Rotating Zones)",
        rules_sec_70: "SEC 70: THE VOID (Absorb Bullets)",
        strategy_tip: "STRATEGY: Visit the DATA_SHOP! Upgrade Firepower, Speed, and install SHIELDS to survive.",
        invite: "👥 INVITE FRIEND +500", invite_done: "INVITATION SENT ✓", claimed: "BONUS CLAIMED ✓",
        active_label: "EQUIPPED", stars_label: "STARS",
        achievementss: "--- ACHIEVEMENTS ---", fx_title: "--- VISUAL FX ---", up_title: "--- SHIP UPGRADES ---",
        fx_rainbow: "RAINBOW TRAIL", desc_rainbow: "Leave a colorful trail behind",
        flawlesst: "FLAWLESS", boss_damage: "Boss: 0 damage",
        tycoon: "TYCOON", rich_credit: "5000 credits",
        marathons: "MARATHON", run_m: "5000m run",
        sharpshooter: "SNIPER", snipe_desc: "Defeat boss with overdrive only",
        speedster: "SPEEDSTER", speed_desc: "Reach 2000m in one run",
        collector: "COLLECTOR", collect_desc: "Collect 1000 coins in one run",
        survivor10: "SURVIVOR", surv10_desc: "Survive 10 boss fights",
        survivor50: "IRON WILL", surv50_desc: "Survive 50 boss fights",
        bossSlayer: "SLAYER", boss_desc: "Defeat 25 bosses",
        achievement_unlocked: "ACHIEVEMENT UNLOCKED!",
        daily_quests: "--- DAILY QUESTS ---", daily_complete: "DONE",
        rank_label: "RANK", rank_xp: "XP", rank_rookie: "ROOKIE", rank_pilot: "PILOT",
        rank_elite: "ELITE", rank_master: "MASTER", rank_legend: "LEGEND",
        rank_up: "RANK UP!", rank_reached: "You reached a new rank!",
        quest_kill50: "Kill 50 minions", quest_kill50_desc: "Reward: +150 Credits",
        quest_noshield: "Reach boss without shield", quest_noshield_desc: "Reward: +200 Credits",
        quest_combo15: "Collect combo x15", quest_combo15_desc: "Reward: +100 Credits",
        quest_clearboss: "Defeat any boss", quest_clearboss_desc: "Reward: +250 Credits",
        quest_complete: "QUEST COMPLETE!",
        change_name: "[ CHANGE NAME ]", ship_name: "Enter ship name:"
    },
    ru: {
        menu_title: "ГЛИТЧ\nАРЕНА", start: ">> ЗАПУСК СИСТЕМЫ", shop: ">> МАГАЗИН ДАННЫХ",
        hangar: ">> АНГАР КОРАБЛЯ", settings: ">> КАЛИБРОВКА", rules: ">> ИНСТРУКЦИЯ",
        top: ">> РЕЙТИНГ ПИЛОТОВ", audio: "ЗВУК", back: "<< В ГЛАВНОЕ МЕНЮ",
        offset_label: "ОТСТУП", higher: "ВЫШЕ", lower: "НИЖЕ", apply: "<< ПРИМЕНИТЬ",
        share_duel: "⚔️ ВЫЗВАТЬ НА ДУЭЛЬ", profile: "[ ПРОФИЛЬ ]",
        credits: "КРЕДИТЫ", sector: "СЕКТОР", best: "РЕКОРД", max_dist: "ДИСТАНЦИЯ",
        hp_label: "ОЗ", core_label: "ЯДРО", tap_ultra: "!! ЖМИ ДЛЯ УЛЬТЫ !!",
        combo_text: "КОМБО", hyper_glitch: "!!! ГИПЕР-ГЛИТЧ: 3x ЗОЛОТО !!!",
        pause_text: "ПАУЗА", v_on: "ВКЛ", v_off: "ВЫКЛ",
        p1: ["СКАНИРОВАНИЕ...", "ЦЕЛЬ_ЗАХВАЧЕНА", "НАРУШИТЕЛЬ_ДАННЫХ"],
        p2: ["ПЕРЕГРУЗКА_СИСТЕМЫ", "КРИТИЧЕСКАЯ_ЯРОСТЬ", "УДАЛЕНИЕ_ОБЪЕКТА"],
        wall_p1: ["СМЕНА_ЗОНЫ", "ВЫБИРАЙ_МУДРО", "СТЕНА_ЖДЁТ"],
        wall_p2: ["НЕТ_ПОБЕГА", "УНИЧТОЖЕНИЕ", "СТЕНА_ДАВИТ"],
        dual_p1: ["СИЛА_БЛИЗНЕЦОВ", "СИНХРОНИЗАЦИЯ", "ДВА_ЯДРА"],
        dual_p2: ["ПЕРЕГРУЗКА", "ПРОРЫВ", "СИСТЕМА_ПАДАЕТ"],
        storm_p1: ["ШТОРМ_ИДЕТ", "ЗОНЫ_ВРАЩАЮТСЯ", "ХАОС_БЛИЗКО"],
        storm_p2: ["РЕЖИМ_ТОРНАДО", "ШТОРМ_ЛОМАЕТ", "РАЗРУШЕНИЕ_КРУТИТСЯ"],
        void_p1: ["ПУСТОТА_ОТКРЫВАЕТСЯ", "ПОГЛОЩЕНИЕ_СИЛЫ", "ТЬМА_ПИТАЕТСЯ"],
        void_p2: ["ПУСТОТА_ВЫСВОБОЖДЕНА", "ТЁМНАЯ_МАТЕРИЯ", "ПОГЛОЩЕН_НИЧТОМ"],
        core_destroyed: "ЯДРО УНИЧТОЖЕНО!", boss_detected: "ОБНАРУЖЕН_МЕГА_БОСС",
        defense_engaged: "ЭЛИТНАЯ_ЗАЩИТА_АКТИВНА", critical_race: "КРИТИЧЕСКАЯ ЯРОСТЬ",
        system_halt: "!! СИСТЕМНАЯ ОСТАНОВКА: ПЕРЕГРУЗКА ЯДРА !!", warning_boss: "!! ВНИМАНИЕ !!\nБОСС ПРИБЛИЖАЕТСЯ",
        quantum_alert: "ОБНАРУЖЕН_КВАНТОВЫЙ_ФАНТОМ", integrity_restored: "КОРПУС ВОССТАНОВЛЕН",
        wall_zone: "ОПАСНАЯ ЗОНА!", wall_safe: "БЕЗОПАСНО!",
        audio_glitch: "ОШИБКА_АУДИО_СИСТЕМЫ", sys_failure: "!! СИСТЕМНЫЙ_СБОЙ !!",
        heroic_survival: "ГЕРОИЧЕСКОЕ_ВЫЖИВАНИЕ", lost: "СВЯЗЬ ПОТЕРЯНА",
        revive_label: "ВОСКРЕСНУТЬ", watch_ad_label: "РЕКЛАМА (БЕСПЛАТНЫЙ РЕБУТ)",
        hard_reboot_label: "ХАРД-РЕБУТ (СЕКТОР 1)",
        share_invite: "Я в Секторе %lvl%! Побей мой рекорд в %dist%м в Glitched Arena!",
        share_win_text: "Я зачистил Сектор %lvl% в Глитч Арене! Попробуй повторить!",
        share_loss_text: "Моя система дала сбой в Секторе %lvl%... Кто отомстит за меня?",
        db_connecting: "ПОДКЛЮЧЕНИЕ_К_БАЗЕ_ДАННЫХ...", db_empty: "ЗАПИСЕЙ ПОКА НЕТ", db_error: "ОШИБКА_СВЯЗИ: ОФФЛАЙН",
        shop_title: "МАГАЗИН ДАННЫХ", maxed: "МАКСИМУМ", deploy_btn: ">> В СЛЕД. СЕКТОР",
        hangar_title: "АНГАР КОРАБЛЯ", hull_type: "--- ТИП КОРПУСА ---", visual_skin: "--- ОБЛИК ---",
        target: "ЦЕЛЬ", suggest: "СОВЕТ", classic_box: "КЛАССИКА", cyan_neon: "ГОЛУБОЙ НЕОН",
        boss_scanning: "СЕКТОР_СКАН_", rules_header: "ИНСТРУКЦИЯ v1.2",
        callsign_label: "--- ПОЗЫВНОЙ ---", tap_edit: "[ ТЫКНИ ДЛЯ СМЕНЫ ]",
        to_mega_boss: "ДО МЕГА_БОССА", elite_phase: "ЭЛИТНАЯ ФАЗА", distance_to: "РАССТОЯНИЕ ДО БОССА",
        purified: "СИСТЕМА ОЧИЩЕНА", magnet_on: "МАГНИТНЫЙ ЗАХВАТ", time_warp: "ВРЕМЯ ЗАМЕДЛЕНО",
        underst: "[ Я ПРИНЯЛ ]",
        gary_intro: "Смотрите-ка... новый «пилот». Постарайся не сломать мою систему, ладно? Трать Кредиты на пушки, иначе не продержишься и секунды. Удачи, белковый.",
        gary_intro_ship: "О, ты назвал эту жестянку «%ship%»? Мило. Надеюсь, она горит так же красиво, как и называется. Слушай сюда...",
        up_antenna: "УЛЬТРА-АНТЕННА", desc_antenna: "Зарядка ульты на 75% быстрее",
        up_cannons: "ДВОЙНЫЕ ПУШКИ", desc_cannons: "Тройная огневая мощь",
        up_speed: "УСКОРЕНИЕ", desc_speed: "+10% к скорости полета",
        up_hull: "УСИЛЕННЫЙ КОРПУС", desc_hull: "+25 макс. ОЗ и лечение",
        up_shield: "АВАРИЙНЫЙ ЩИТ", desc_shield: "Защита от одного удара",
        skin_striker: "РАССЕКАТЕЛЬ БЕЗДНЫ", desc_striker: "Форма треугольника (+20% АТК)",
        skin_gold: "ЗОЛОТОЙ ОБЛИК", desc_gold: "Стиль из чистого золота (+10% АТК)",
        skin_ghost: "НЕОНОВЫЙ ПРИЗРАК", desc_ghost: "Призрачный стиль (+15% СКОР)",
        skin_crimson: "КРАСНЫЙ", desc_crimson: "Кровавый +5% крит урон по боссу",
        skin_void: "ПУСТОТА", desc_void: "Тёмный +3% уклонение от босс-пуль",
        skin_plasma: "ПЛАЗМА", desc_plasma: "Неоновый +5% скорость зарядки ульты",
        skin_solar: "СОЛНЕЧНЫЙ", desc_solar: "Золотистый +10% монеты с миньонов",
        skin_frost: "МОРОЗ", desc_frost: "Ледяной +1сек длительность замедления",
        skin_rainbow: "РАДУГА", desc_rainbow: "Радужный шлейф +3x бонус комбо",
        void_premium: "ВЛАСТЕЛИН ПУСТОТЫ", desc_void_premium: "Тёмный щит блокирует 1 удар",
        crystal: "КРИСТАЛЛ", desc_crystal: "Отражает пули +1сек замедление",
        up_omega: "ОМЕГА-ЯДРО", desc_omega: "Доступно с 40 уровня. Ульта восстанавливается при каждом уничтожении миньона!",
        ship_tank: "БРОНЕНОСЕЦ", desc_tank: "+35 ОЗ, -8% Скорость",
        ship_dart: "СТРЕЛА", desc_dart: "+20% Скорость, -10% Атака",
        ship_viper: "ГАДЮКА", desc_viper: "Боковые выстрелы каждые 5 ударов",
        ship_phase: "ФАЗОВИК", desc_phase: "10% шанс увернуться от стен",
        up_coins: "ПАКЕТ ДАННЫХ", desc_coins: "+1000 Кредитов мгновенно",
        fx_blue_exp: "ГОЛУБОЙ ВЗРЫВ", desc_blue_exp: "Корабль взрывается неоновым синим",
        fx_pink_exp: "РОЗОВЫЙ ВЗРЫВ", desc_pink_exp: "Корабль взрывается розовым глитчем",
        fx_rainbow_exp: "РАДУЖНЫЙ ВЗРЫВ", desc_rainbow_exp: "Разноцветный взрыв",
        fx_gold_exp: "ЗОЛОТОЙ ВЗРЫВ", desc_gold_exp: "Искрящийся золотой взрыв",
        fx_green_exp: "НЕОНОВЫЙ ЗЕЛЕНЫЙ", desc_green_exp: "Токсичный зеленый взрыв",
        fx_red_exp: "КРАСНАЯ ТРЕВОГА", desc_red_exp: "Опасный красный взрыв",
        bundle_starter: "СТАРТОВЫЙ НАБОР", bundle_starter_desc: "Золотой скин + Антенна + Ускорение",
        bundle_warrior: "ВОИН", bundle_warrior_desc: "Красный скин + Двойные пушки + Улучшение корпуса",
        bundle_legend: "ЛЕГЕНДА", bundle_legend_desc: "Радуга + Властелин пустоты + Омега-Ядро",
        helper_drone: "БОЕВОЙ ДРОН", desc_helper_drone: "Авто-огонь 2 снарядами каждые 0.8сек",
        helper_missile: "РАКЕТНЫЙ ДРОН", desc_helper_missile: "Самонаводящиеся ракеты каждые 1.5с",
        helper_autoshield: "АВТО-ЩИТ", desc_helper_autoshield: "Блокирует 1 удар за сектор",
        helper_autobomb: "ПОСМЕРТНЫЙ ВЗРЫВ", desc_helper_autobomb: "Уничтожает снаряды, 80% урона боссу",
        helper_autoheal: "АВТО-РЕМОНТ", desc_helper_autoheal: "Лечит 10 HP каждые 2.5сек",
        helper_mercenary: "НАЁМНИК (1 ВЫЛЕТ)", desc_helper_mercenary: "Мощный дрон-помощник на 1 игру",
        up_extralife: "ЭКСТРА-ЖИЗНЬ", desc_up_extralife: "+1 возрождение за сектор (макс 5)",
        up_doubleDMG: "ПЕРЕГРУЗКА", desc_up_doubleDMG: "2x урон на 30сек после смерти",
        up_enhanced: "ТИТАНОВЫЙ АПГРЕЙД", desc_up_enhanced: "2x эффект апгрейдов, сект. 50+",
        rule_wall: "СТЕНА: Смертельно. Избегай!", rule_coin: "КРЕДИТЫ: Для улучшений.",
        rule_heart: "СЕРДЦЕ: +25% прочности.", rule_nuke: "ЯДЕРКА: Очистка экрана.",
        rule_magnet: "МАГНИТ: Притягивает золото.", rule_slowmo: "ЗАМЕДЛЕНИЕ: Контроль времени.",
        combo_tip: "КОМБО: Уклоняйся от препятствий, сбрасывается при ударе!",
        rules_alerts: "--- ТРЕВОГИ СЕКТОРОВ ---", slide: "ВЕДИ, ЧТОБЫ ДВИГАТЬСЯ",
        rules_sec_15: "СЕКТОР 15: МЕГА_БОСС (Боковые турели)", rules_sec_20: "СЕКТОР 20: ЭЛИТНЫЕ ЩИТЫ (Орбитальная защита)",
        rules_sec_30: "СЕКТОР 30: ПЕРЕГРУЗКА ЯДРА (Безумный огонь)", rules_sec_35: "СЕКТОР 35: КВАНТОВЫЙ ФАНТОМ (Телепортация)",
        rules_sec_40: "СЕКТОР 40: СТЕНА (Уклонение от зон)",
        rules_sec_50: "СЕКТОР 50: ДВА ЯДРА (Близнецы)",
        rules_sec_60: "СЕКТОР 60: ШТОРМ (Вращающиеся зоны)",
        rules_sec_70: "СЕКТОР 70: ПУСТОТА (Поглощение пуль)",
        strategy_tip: "СТРАТЕГИЯ: Зайди в МАГАЗИН! Качай пушки, скорость и ставь ЩИТЫ, чтобы выжить.",
        invite: "👥 ПРИГЛАСИТЬ ДРУГА +500", invite_done: "ПРИГЛАШЕНИЕ ОТПРАВЛЕНО ✓", claimed: "БОНУС ПОЛУЧЕН ✓",
        active_label: "ВЫБРАНО", stars_label: "ЗВЕЗДЫ",
        achievementss: "--- ДОСТИЖЕНИЯ ---", fx_title: "--- СПЕЦЭФФЕКТЫ ---", up_title: "--- ПРОКАЧКА КОРАБЛЯ ---",
        fx_rainbow: "РАДУЖНЫЙ ШЛЕЙФ", desc_rainbow: "Радуга тянется за вашим кораблем",
        flawlesst: "БЕЗУПРЕЧНЫЙ", boss_damage: "Босс без урона",
        tycoon: "МАГНАТ", rich_credit: "Накопил 5000$",
        marathons: "МАРАФОНЕЦ", run_m: "5000м за вылет",
        sharpshooter: "СНАЙПЕР", snipe_desc: "Убей босса только ультой",
        speedster: "СПРИНТЕР", speed_desc: "Достигни 2000м за один забег",
        collector: "КОЛЛЕКЦИОНЕР", collect_desc: "Собери 1000 монет за один забег",
        survivor10: "ВЫЖИВШИЙ", surv10_desc: "Переживи 10 боёв с боссами",
        survivor50: "ЖЕЛЕЗНАЯ ВОЛЯ", surv50_desc: "Переживи 50 боёв с боссами",
        bossSlayer: "УБИЙЦА", boss_desc: "Убей 25 боссов",
        achievement_unlocked: "ДОСТИЖЕНИЕ ОТКРЫТО!",
        daily_quests: "--- ЕЖЕДНЕВНЫЕ ЗАДАНИЯ ---", daily_complete: "ГОТОВО",
        rank_label: "РАНГ", rank_xp: "ОПЫТ", rank_rookie: "НОВИЧОК", rank_pilot: "ПИЛОТ",
        rank_elite: "ЭЛИТА", rank_master: "МАСТЕР", rank_legend: "ЛЕГЕНДА",
        rank_up: "ПОВЫШЕНИЕ РАНГА!", rank_reached: "Вы достигли нового ранга!",
        quest_kill50: "Убей 50 приспешников", quest_kill50_desc: "Награда: +150 💰",
        quest_noshield: "Доберись до босса без щита", quest_noshield_desc: "Награда: +200 💰",
        quest_combo15: "Собери комбо х15", quest_combo15_desc: "Награда: +100 💰",
        quest_clearboss: "Убей любого босса", quest_clearboss_desc: "Награда: +250 💰",
        quest_complete: "ЗАДАНИЕ ВЫПОЛНЕНО!",
        change_name: "[ ИЗМЕНИТЬ ИМЯ ]", ship_name: "Введите имя корабля:"
    }
};