name: Deploy Arena to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: glitched-arena.myftp.org
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/glitched-arena
            git fetch --all
            git reset --hard origin/main
            systemctl restart glitched-arena.service
